name: Deploy Battle AI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NG_CLI_ANALYTICS: "false"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Depenedencies
        run: |
          npm install -g @angular/cli
          npm install

      - name: Build Map Editor
        run: npm run build -- --output-path dist --base-href /homm3-battle-ai/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
